Update README.md (#47)
The set_type method of a SmartVmCreator had been changed, now it takes the SMART package id and the package id has to be retrieved by the get_package_id of the CloudInterface class.
With the old README version you got this:

>>> c.set_type(size='small')
...
TypeError: set_type() got an unexpected keyword argument 'size'